### PR TITLE
No redirects, please

### PR DESCRIPTION
**Pull request by hashbrowncipher**
If a service being healthchecked happens to return a redirect, I want to treat that as healthy.  If it needs to know about some upstream service's health, that's its job to do, not mine.  Don't follow redirects.

### CODE REVIEW

**Comment by EvanKrall** [comment]
Will this cause hacheck to forward the 301 along to the client?

**Comment by hashbrowncipher** [comment]
Yes.  HAProxy, for instance, will treat that as healthy:

> By default, "option httpchk" considers that response statuses 2xx and 3xx
are valid, and that others are invalid.

**Comment by EvanKrall** [comment]
Nerve does not:

```ruby
       if code >= 200 and code < 300 and (@expect == nil || body.include?(@expect))
          log.debug "nerve: check #{@name} got response code #{code} with body \"#{body}\""
          return true
        else
          log.warn "nerve: check #{@name} got response code #{code} with body \"#{body}\""
          return false
        end
```

**Comment by hashbrowncipher** [comment]
hmm.  That means that if nerve is pointed at a service which returns 301s for its healthcheck, it will be treated as unhealthy.  So (IMO) this is a problem of the upstream service not fulfilling nerve's healthcheck, and not hacheck's fault for failing to transmute the result into a 200.  Alternatively, we could view it as nerve's problem, because nerve fails to match the behavior of other healthcheckers:

nginx:
> by default, the response should have status code 2xx or 3xx.

**Comment by EvanKrall** [comment]
I do think this is a fairly big change in interface, so please don't deploy this change yet. The service that was throwing 301s will be deregistered from smartstack when we deploy this.

I'm not sure what my preferred behavior is for status codes 3xx. I guess there are 4 valid options:

 - follow redirects
 - return the status code verbatim (and, I guess, the Location header?)
 - translate them to 2xx
 - translate them to 4xx or 5xx

Should this be configurable? Should we just pick one?

**Comment by jolynch** [comment]
@EvanKrall personally I think nerve seems broken here if it considers 3xx failure. If haproxy, nginx, and marathon all consider 3xx healthy then Nerve should too imo.

**Comment by EvanKrall** [comment]
@hashbrowncipher can you duplicate this PR on upstream?

**Comment by jolynch** [comment]
@EvanKrall I just merged https://github.com/airbnb/nerve/pull/78 which should alleviate your concern.

**Pull request merged**
